--
-- PostgreSQL database dump
--

\restrict C3ROqTHgMhRzI30mwOm5MQ2lb0AwMxf9OaCvuQMAgz2rihfXVPhzV6BjkT2sgTO

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: hstore; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS hstore WITH SCHEMA public;


--
-- Name: EXTENSION hstore; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION hstore IS 'data type for storing sets of (key, value) pairs';


--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: azure_ad_audit_log_v2; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.azure_ad_audit_log_v2 (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    user_id uuid,
    event_type character varying(255),
    description text,
    action character varying(255),
    details jsonb DEFAULT '{}'::jsonb,
    ip_address character varying(45),
    user_agent text,
    request_id character varying(255),
    status character varying(50) DEFAULT 'success'::character varying,
    error_message text,
    metadata jsonb DEFAULT '{}'::jsonb,
    "timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: azure_sso_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.azure_sso_config (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    azure_tenant_id character varying(255) NOT NULL,
    client_id character varying(255) NOT NULL,
    client_secret text NOT NULL,
    authority character varying(500),
    authorization_endpoint character varying(500),
    token_endpoint character varying(500),
    scim_enabled boolean DEFAULT false,
    scim_token character varying(255),
    scim_base_url character varying(500),
    auto_provision_users boolean DEFAULT true,
    auto_deprovision_users boolean DEFAULT true,
    sync_user_attributes boolean DEFAULT true,
    attribute_mapping jsonb DEFAULT '{}'::jsonb,
    group_role_mapping jsonb DEFAULT '{}'::jsonb,
    last_sync_at timestamp with time zone,
    last_sync_status character varying(50),
    last_sync_error text,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: compliance_overviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.compliance_overviews (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    framework character varying(255) NOT NULL,
    provider_id uuid NOT NULL,
    compliance_score numeric(5,2),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: compliance_requirements_overviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.compliance_requirements_overviews (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    requirement_id character varying(255) NOT NULL,
    compliance_overview_id uuid NOT NULL,
    status character varying(50) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: findings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.findings (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    check_id character varying(255) NOT NULL,
    status character varying(50) NOT NULL,
    severity character varying(50) NOT NULL,
    resource_id uuid,
    provider_id uuid NOT NULL,
    scan_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: integration_provider_mappings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.integration_provider_mappings (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    integration_id uuid NOT NULL,
    provider_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: integrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.integrations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(100) NOT NULL,
    tenant_id uuid NOT NULL,
    configuration jsonb,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: invitations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invitations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email character varying(254) NOT NULL,
    tenant_id uuid NOT NULL,
    invited_by_id uuid NOT NULL,
    state character varying(50) DEFAULT 'pending'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    inserted_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    token character varying(500),
    inviter_id uuid
);


--
-- Name: memberships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.memberships (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    role character varying(50) NOT NULL,
    date_joined timestamp with time zone DEFAULT now() NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    joined_at timestamp with time zone DEFAULT now(),
    invited_by_id uuid,
    can_invite_users boolean DEFAULT false,
    can_manage_settings boolean DEFAULT false,
    can_view_analytics boolean DEFAULT true
);


--
-- Name: provider_group_memberships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_group_memberships (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    provider_id uuid NOT NULL,
    provider_group_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: provider_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_groups (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    tenant_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    inserted_at timestamp with time zone
);


--
-- Name: provider_secrets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_secrets (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    provider_id uuid NOT NULL,
    secret_key character varying(255) NOT NULL,
    secret_value text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: providers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.providers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    provider_type character varying(50) NOT NULL,
    tenant_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    is_active boolean DEFAULT true NOT NULL
);


--
-- Name: resource_finding_mappings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resource_finding_mappings (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    resource_id uuid NOT NULL,
    finding_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: resource_scan_summaries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resource_scan_summaries (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    resource_id uuid NOT NULL,
    scan_id uuid NOT NULL,
    findings_count integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: resource_tag_mappings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resource_tag_mappings (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    resource_id uuid NOT NULL,
    resource_tag_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: resource_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resource_tags (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    key character varying(255) NOT NULL,
    value character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: resources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resources (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    resource_id character varying(255) NOT NULL,
    resource_type character varying(255) NOT NULL,
    provider_id uuid NOT NULL,
    region character varying(100),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: role_invitation_relationship; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_invitation_relationship (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    role_id uuid NOT NULL,
    invitation_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: role_provider_group_relationship; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_provider_group_relationship (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    role_id uuid NOT NULL,
    provider_group_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: role_user_relationship; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_user_relationship (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    role_id uuid NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    tenant_id uuid NOT NULL,
    permissions text,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    manage_users boolean DEFAULT false,
    manage_account boolean DEFAULT false,
    manage_billing boolean DEFAULT false,
    manage_providers boolean DEFAULT false,
    manage_integrations boolean DEFAULT false,
    manage_scans boolean DEFAULT false,
    unlimited_visibility boolean DEFAULT false
);


--
-- Name: scan_summaries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scan_summaries (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    scan_id uuid NOT NULL,
    total_findings integer DEFAULT 0 NOT NULL,
    critical_findings integer DEFAULT 0 NOT NULL,
    high_findings integer DEFAULT 0 NOT NULL,
    medium_findings integer DEFAULT 0 NOT NULL,
    low_findings integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: scans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scans (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    provider_id uuid NOT NULL,
    status character varying(50) DEFAULT 'pending'::character varying NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: security_audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.security_audit_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    tenant_id uuid,
    event_type character varying(50) NOT NULL,
    event_description text,
    ip_address inet,
    user_agent text,
    metadata jsonb DEFAULT '{}'::jsonb,
    severity character varying(20) DEFAULT 'info'::character varying,
    created_at timestamp with time zone DEFAULT now(),
    "timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    request_path character varying(500),
    request_method character varying(10),
    message text DEFAULT ''::text NOT NULL,
    details jsonb DEFAULT '{}'::jsonb,
    is_security_violation boolean DEFAULT false,
    requires_investigation boolean DEFAULT false,
    resolved boolean DEFAULT false,
    resolved_by_id uuid,
    resolved_at timestamp with time zone,
    resolution_notes text
);


--
-- Name: tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tasks (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(50) DEFAULT 'pending'::character varying NOT NULL,
    tenant_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: tenant_memberships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenant_memberships (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    role character varying(50) DEFAULT 'member'::character varying NOT NULL,
    joined_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    can_manage_users boolean DEFAULT false NOT NULL,
    can_manage_billing boolean DEFAULT false NOT NULL,
    can_manage_providers boolean DEFAULT false NOT NULL,
    can_manage_scans boolean DEFAULT false NOT NULL,
    can_manage_integrations boolean DEFAULT false NOT NULL,
    unlimited_visibility boolean DEFAULT false NOT NULL,
    invited_by_id uuid,
    can_invite_users boolean DEFAULT false,
    can_manage_settings boolean DEFAULT false,
    can_delete_tenant boolean DEFAULT false,
    last_accessed_at timestamp with time zone,
    invitation_token character varying(255),
    invitation_expires_at timestamp with time zone,
    tenant uuid,
    invited_by uuid,
    can_view_analytics boolean DEFAULT false NOT NULL,
    can_run_scans boolean DEFAULT false,
    can_export_reports boolean DEFAULT false,
    invited_at timestamp without time zone,
    invite_accepted_at timestamp without time zone,
    invite_token character varying(500) DEFAULT ''::character varying,
    invite_expires_at timestamp without time zone
);


--
-- Name: tenants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenants (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    inserted_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    domain character varying(255),
    subdomain character varying(255),
    trial_ends_at timestamp with time zone,
    contact_email character varying(255),
    contact_phone character varying(50),
    address text,
    logo_url character varying(2048),
    theme_color character varying(20),
    secondary_color character varying(20),
    is_verified boolean DEFAULT false,
    admin_user_id integer,
    subscription_status character varying(20) DEFAULT 'trial'::character varying,
    allow_registration boolean DEFAULT true,
    require_email_verification boolean DEFAULT false,
    session_timeout_minutes integer DEFAULT 480,
    created_by_id uuid,
    last_activity timestamp with time zone,
    max_users integer DEFAULT 5 NOT NULL,
    subscription_tier character varying(50) DEFAULT 'free'::character varying NOT NULL,
    max_providers integer DEFAULT 10,
    max_scans integer DEFAULT 100,
    max_members integer DEFAULT 10,
    features_enabled jsonb DEFAULT '{}'::jsonb,
    settings jsonb DEFAULT '{}'::jsonb,
    metadata jsonb DEFAULT '{}'::jsonb,
    lockout_duration_minutes integer DEFAULT 30,
    max_failed_login_attempts integer DEFAULT 5,
    last_security_scan timestamp without time zone
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id integer NOT NULL,
    user_id uuid,
    jti character varying(255) NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL
);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.token_blacklist_outstandingtoken_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.token_blacklist_outstandingtoken_id_seq OWNED BY public.token_blacklist_outstandingtoken.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    name character varying(255),
    email character varying(254) NOT NULL,
    company_name character varying(255),
    is_active boolean DEFAULT true NOT NULL,
    date_joined timestamp with time zone DEFAULT now() NOT NULL,
    trial_start timestamp with time zone,
    trial_end timestamp with time zone,
    is_trial_active boolean DEFAULT false NOT NULL,
    primary_tenant_id uuid,
    is_verified boolean DEFAULT false,
    last_login_ip inet,
    failed_login_attempts integer DEFAULT 0,
    locked_until timestamp with time zone,
    is_superuser boolean DEFAULT false NOT NULL,
    is_staff boolean DEFAULT false NOT NULL,
    first_name character varying(150) DEFAULT ''::character varying,
    last_name character varying(150) DEFAULT ''::character varying,
    username character varying(150),
    password_changed_at timestamp with time zone,
    two_factor_enabled boolean DEFAULT false,
    two_factor_secret character varying(32),
    security_notes text,
    last_security_scan timestamp with time zone,
    security_score integer DEFAULT 0,
    risk_level character varying(20) DEFAULT 'low'::character varying,
    compliance_status character varying(20) DEFAULT 'unknown'::character varying,
    data_retention_days integer DEFAULT 365,
    privacy_level character varying(20) DEFAULT 'standard'::character varying,
    audit_enabled boolean DEFAULT true,
    notification_preferences jsonb DEFAULT '{}'::jsonb,
    timezone character varying(50) DEFAULT 'UTC'::character varying,
    language character varying(10) DEFAULT 'en'::character varying,
    azure_id character varying(255),
    azure_tenant_id character varying(255),
    azure_upn character varying(255),
    department character varying(255) DEFAULT ''::character varying,
    job_title character varying(255) DEFAULT ''::character varying,
    phone_number character varying(50) DEFAULT ''::character varying,
    manager_azure_id character varying(255) DEFAULT ''::character varying,
    is_sso_user boolean DEFAULT false,
    deactivated_at timestamp without time zone,
    deactivation_reason character varying(50) DEFAULT ''::character varying,
    invited_at timestamp without time zone,
    accepted_invite_at timestamp without time zone,
    first_login_at timestamp without time zone,
    onboarding_completed_at timestamp without time zone
);


--
-- Name: token_blacklist_outstandingtoken id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken ALTER COLUMN id SET DEFAULT nextval('public.token_blacklist_outstandingtoken_id_seq'::regclass);


--
-- Name: azure_ad_audit_log_v2 azure_ad_audit_log_v2_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.azure_ad_audit_log_v2
    ADD CONSTRAINT azure_ad_audit_log_v2_pkey PRIMARY KEY (id);


--
-- Name: azure_sso_config azure_sso_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.azure_sso_config
    ADD CONSTRAINT azure_sso_config_pkey PRIMARY KEY (id);


--
-- Name: compliance_overviews compliance_overviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.compliance_overviews
    ADD CONSTRAINT compliance_overviews_pkey PRIMARY KEY (id);


--
-- Name: compliance_requirements_overviews compliance_requirements_overviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.compliance_requirements_overviews
    ADD CONSTRAINT compliance_requirements_overviews_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: findings findings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.findings
    ADD CONSTRAINT findings_pkey PRIMARY KEY (id);


--
-- Name: integration_provider_mappings integration_provider_mappings_integration_id_provider_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.integration_provider_mappings
    ADD CONSTRAINT integration_provider_mappings_integration_id_provider_id_key UNIQUE (integration_id, provider_id);


--
-- Name: integration_provider_mappings integration_provider_mappings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.integration_provider_mappings
    ADD CONSTRAINT integration_provider_mappings_pkey PRIMARY KEY (id);


--
-- Name: integrations integrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.integrations
    ADD CONSTRAINT integrations_pkey PRIMARY KEY (id);


--
-- Name: invitations invitations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT invitations_pkey PRIMARY KEY (id);


--
-- Name: memberships memberships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT memberships_pkey PRIMARY KEY (id);


--
-- Name: memberships memberships_user_id_tenant_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT memberships_user_id_tenant_id_key UNIQUE (user_id, tenant_id);


--
-- Name: provider_group_memberships provider_group_memberships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_group_memberships
    ADD CONSTRAINT provider_group_memberships_pkey PRIMARY KEY (id);


--
-- Name: provider_group_memberships provider_group_memberships_provider_id_provider_group_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_group_memberships
    ADD CONSTRAINT provider_group_memberships_provider_id_provider_group_id_key UNIQUE (provider_id, provider_group_id);


--
-- Name: provider_groups provider_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_groups
    ADD CONSTRAINT provider_groups_pkey PRIMARY KEY (id);


--
-- Name: provider_secrets provider_secrets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_secrets
    ADD CONSTRAINT provider_secrets_pkey PRIMARY KEY (id);


--
-- Name: providers providers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.providers
    ADD CONSTRAINT providers_pkey PRIMARY KEY (id);


--
-- Name: resource_finding_mappings resource_finding_mappings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_finding_mappings
    ADD CONSTRAINT resource_finding_mappings_pkey PRIMARY KEY (id);


--
-- Name: resource_finding_mappings resource_finding_mappings_resource_id_finding_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_finding_mappings
    ADD CONSTRAINT resource_finding_mappings_resource_id_finding_id_key UNIQUE (resource_id, finding_id);


--
-- Name: resource_scan_summaries resource_scan_summaries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_scan_summaries
    ADD CONSTRAINT resource_scan_summaries_pkey PRIMARY KEY (id);


--
-- Name: resource_scan_summaries resource_scan_summaries_resource_id_scan_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_scan_summaries
    ADD CONSTRAINT resource_scan_summaries_resource_id_scan_id_key UNIQUE (resource_id, scan_id);


--
-- Name: resource_tag_mappings resource_tag_mappings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_tag_mappings
    ADD CONSTRAINT resource_tag_mappings_pkey PRIMARY KEY (id);


--
-- Name: resource_tag_mappings resource_tag_mappings_resource_id_resource_tag_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_tag_mappings
    ADD CONSTRAINT resource_tag_mappings_resource_id_resource_tag_id_key UNIQUE (resource_id, resource_tag_id);


--
-- Name: resource_tags resource_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_tags
    ADD CONSTRAINT resource_tags_pkey PRIMARY KEY (id);


--
-- Name: resources resources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT resources_pkey PRIMARY KEY (id);


--
-- Name: role_invitation_relationship role_invitation_relationship_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_invitation_relationship
    ADD CONSTRAINT role_invitation_relationship_pkey PRIMARY KEY (id);


--
-- Name: role_invitation_relationship role_invitation_relationship_role_id_invitation_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_invitation_relationship
    ADD CONSTRAINT role_invitation_relationship_role_id_invitation_id_key UNIQUE (role_id, invitation_id);


--
-- Name: role_provider_group_relationship role_provider_group_relationship_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_provider_group_relationship
    ADD CONSTRAINT role_provider_group_relationship_pkey PRIMARY KEY (id);


--
-- Name: role_provider_group_relationship role_provider_group_relationship_role_id_provider_group_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_provider_group_relationship
    ADD CONSTRAINT role_provider_group_relationship_role_id_provider_group_id_key UNIQUE (role_id, provider_group_id);


--
-- Name: role_user_relationship role_user_relationship_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_user_relationship
    ADD CONSTRAINT role_user_relationship_pkey PRIMARY KEY (id);


--
-- Name: role_user_relationship role_user_relationship_role_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_user_relationship
    ADD CONSTRAINT role_user_relationship_role_id_user_id_key UNIQUE (role_id, user_id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: scan_summaries scan_summaries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scan_summaries
    ADD CONSTRAINT scan_summaries_pkey PRIMARY KEY (id);


--
-- Name: scans scans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scans
    ADD CONSTRAINT scans_pkey PRIMARY KEY (id);


--
-- Name: security_audit_logs security_audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.security_audit_logs
    ADD CONSTRAINT security_audit_logs_pkey PRIMARY KEY (id);


--
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);


--
-- Name: tenant_memberships tenant_memberships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_memberships
    ADD CONSTRAINT tenant_memberships_pkey PRIMARY KEY (id);


--
-- Name: tenants tenants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_key UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: tenant_memberships unique_user_tenant_membership; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_memberships
    ADD CONSTRAINT unique_user_tenant_membership UNIQUE (user_id, tenant_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: findings_provider_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX findings_provider_id_idx ON public.findings USING btree (provider_id);


--
-- Name: findings_resource_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX findings_resource_id_idx ON public.findings USING btree (resource_id);


--
-- Name: findings_scan_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX findings_scan_id_idx ON public.findings USING btree (scan_id);


--
-- Name: idx_audit_event_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_event_type ON public.security_audit_logs USING btree (event_type);


--
-- Name: idx_audit_investigation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_investigation ON public.security_audit_logs USING btree (requires_investigation);


--
-- Name: idx_audit_ip; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_ip ON public.security_audit_logs USING btree (ip_address);


--
-- Name: idx_audit_resolved; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_resolved ON public.security_audit_logs USING btree (resolved);


--
-- Name: idx_audit_severity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_severity ON public.security_audit_logs USING btree (severity);


--
-- Name: idx_audit_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_tenant ON public.security_audit_logs USING btree (tenant_id);


--
-- Name: idx_audit_timestamp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_timestamp ON public.security_audit_logs USING btree ("timestamp");


--
-- Name: idx_audit_timestamp_event; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_timestamp_event ON public.security_audit_logs USING btree ("timestamp", event_type);


--
-- Name: idx_audit_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_user ON public.security_audit_logs USING btree (user_id);


--
-- Name: idx_audit_violation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_violation ON public.security_audit_logs USING btree (is_security_violation);


--
-- Name: idx_azure_audit_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_azure_audit_created ON public.azure_ad_audit_log_v2 USING btree (created_at);


--
-- Name: idx_azure_audit_event_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_azure_audit_event_type ON public.azure_ad_audit_log_v2 USING btree (event_type);


--
-- Name: idx_azure_audit_request; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_azure_audit_request ON public.azure_ad_audit_log_v2 USING btree (request_id);


--
-- Name: idx_azure_audit_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_azure_audit_tenant ON public.azure_ad_audit_log_v2 USING btree (tenant_id);


--
-- Name: idx_azure_audit_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_azure_audit_user ON public.azure_ad_audit_log_v2 USING btree (user_id);


--
-- Name: idx_invitations_token; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invitations_token ON public.invitations USING btree (token);


--
-- Name: idx_membership_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_membership_tenant ON public.tenant_memberships USING btree (tenant_id);


--
-- Name: idx_membership_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_membership_user ON public.tenant_memberships USING btree (user_id);


--
-- Name: idx_membership_user_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_membership_user_tenant ON public.tenant_memberships USING btree (user_id, tenant_id);


--
-- Name: idx_security_audit_logs_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_security_audit_logs_created_at ON public.security_audit_logs USING btree (created_at);


--
-- Name: idx_security_audit_logs_event_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_security_audit_logs_event_type ON public.security_audit_logs USING btree (event_type);


--
-- Name: idx_security_audit_logs_severity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_security_audit_logs_severity ON public.security_audit_logs USING btree (severity);


--
-- Name: idx_security_audit_logs_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_security_audit_logs_tenant_id ON public.security_audit_logs USING btree (tenant_id);


--
-- Name: idx_security_audit_logs_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_security_audit_logs_user_id ON public.security_audit_logs USING btree (user_id);


--
-- Name: idx_tenant_memberships_role; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tenant_memberships_role ON public.tenant_memberships USING btree (role);


--
-- Name: idx_tenant_memberships_tenant_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tenant_memberships_tenant_active ON public.tenant_memberships USING btree (tenant_id, is_active);


--
-- Name: idx_tenant_memberships_user_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tenant_memberships_user_tenant ON public.tenant_memberships USING btree (user_id, tenant_id);


--
-- Name: idx_users_compliance_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_compliance_status ON public.users USING btree (compliance_status);


--
-- Name: idx_users_date_joined; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_date_joined ON public.users USING btree (date_joined);


--
-- Name: idx_users_failed_login_attempts; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_failed_login_attempts ON public.users USING btree (failed_login_attempts);


--
-- Name: idx_users_is_verified; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_is_verified ON public.users USING btree (is_verified);


--
-- Name: idx_users_last_login; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_last_login ON public.users USING btree (last_login);


--
-- Name: idx_users_locked_until; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_locked_until ON public.users USING btree (locked_until);


--
-- Name: idx_users_risk_level; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_risk_level ON public.users USING btree (risk_level);


--
-- Name: idx_users_security_score; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_security_score ON public.users USING btree (security_score);


--
-- Name: memberships_tenant_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX memberships_tenant_id_idx ON public.memberships USING btree (tenant_id);


--
-- Name: memberships_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX memberships_user_id_idx ON public.memberships USING btree (user_id);


--
-- Name: providers_tenant_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX providers_tenant_id_idx ON public.providers USING btree (tenant_id);


--
-- Name: resources_provider_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX resources_provider_id_idx ON public.resources USING btree (provider_id);


--
-- Name: scans_provider_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scans_provider_id_idx ON public.scans USING btree (provider_id);


--
-- Name: token_blacklist_outstandingtoken_jti_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_blacklist_outstandingtoken_jti_idx ON public.token_blacklist_outstandingtoken USING btree (jti);


--
-- Name: token_blacklist_outstandingtoken_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_idx ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: users_email_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_email_idx ON public.users USING btree (email);


--
-- Name: users_is_active_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_is_active_idx ON public.users USING btree (is_active);


--
-- Name: users_name_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_name_idx ON public.users USING btree (name);


--
-- Name: azure_sso_config azure_sso_config_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.azure_sso_config
    ADD CONSTRAINT azure_sso_config_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: compliance_overviews compliance_overviews_provider_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.compliance_overviews
    ADD CONSTRAINT compliance_overviews_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id);


--
-- Name: compliance_requirements_overviews compliance_requirements_overviews_compliance_overview_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.compliance_requirements_overviews
    ADD CONSTRAINT compliance_requirements_overviews_compliance_overview_id_fkey FOREIGN KEY (compliance_overview_id) REFERENCES public.compliance_overviews(id);


--
-- Name: findings findings_provider_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.findings
    ADD CONSTRAINT findings_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id);


--
-- Name: findings findings_resource_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.findings
    ADD CONSTRAINT findings_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES public.resources(id);


--
-- Name: findings findings_scan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.findings
    ADD CONSTRAINT findings_scan_id_fkey FOREIGN KEY (scan_id) REFERENCES public.scans(id);


--
-- Name: tenant_memberships fk_membership_tenant; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_memberships
    ADD CONSTRAINT fk_membership_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: tenant_memberships fk_membership_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_memberships
    ADD CONSTRAINT fk_membership_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: integration_provider_mappings integration_provider_mappings_integration_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.integration_provider_mappings
    ADD CONSTRAINT integration_provider_mappings_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES public.integrations(id);


--
-- Name: integration_provider_mappings integration_provider_mappings_provider_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.integration_provider_mappings
    ADD CONSTRAINT integration_provider_mappings_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id);


--
-- Name: integrations integrations_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.integrations
    ADD CONSTRAINT integrations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: invitations invitations_invited_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT invitations_invited_by_id_fkey FOREIGN KEY (invited_by_id) REFERENCES public.users(id);


--
-- Name: invitations invitations_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT invitations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: memberships memberships_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT memberships_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: memberships memberships_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: provider_group_memberships provider_group_memberships_provider_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_group_memberships
    ADD CONSTRAINT provider_group_memberships_provider_group_id_fkey FOREIGN KEY (provider_group_id) REFERENCES public.provider_groups(id);


--
-- Name: provider_group_memberships provider_group_memberships_provider_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_group_memberships
    ADD CONSTRAINT provider_group_memberships_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id);


--
-- Name: provider_groups provider_groups_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_groups
    ADD CONSTRAINT provider_groups_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: provider_secrets provider_secrets_provider_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_secrets
    ADD CONSTRAINT provider_secrets_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id);


--
-- Name: providers providers_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.providers
    ADD CONSTRAINT providers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: resource_finding_mappings resource_finding_mappings_finding_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_finding_mappings
    ADD CONSTRAINT resource_finding_mappings_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES public.findings(id);


--
-- Name: resource_finding_mappings resource_finding_mappings_resource_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_finding_mappings
    ADD CONSTRAINT resource_finding_mappings_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES public.resources(id);


--
-- Name: resource_scan_summaries resource_scan_summaries_resource_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_scan_summaries
    ADD CONSTRAINT resource_scan_summaries_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES public.resources(id);


--
-- Name: resource_scan_summaries resource_scan_summaries_scan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_scan_summaries
    ADD CONSTRAINT resource_scan_summaries_scan_id_fkey FOREIGN KEY (scan_id) REFERENCES public.scans(id);


--
-- Name: resource_tag_mappings resource_tag_mappings_resource_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_tag_mappings
    ADD CONSTRAINT resource_tag_mappings_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES public.resources(id);


--
-- Name: resource_tag_mappings resource_tag_mappings_resource_tag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_tag_mappings
    ADD CONSTRAINT resource_tag_mappings_resource_tag_id_fkey FOREIGN KEY (resource_tag_id) REFERENCES public.resource_tags(id);


--
-- Name: resources resources_provider_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT resources_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id);


--
-- Name: role_invitation_relationship role_invitation_relationship_invitation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_invitation_relationship
    ADD CONSTRAINT role_invitation_relationship_invitation_id_fkey FOREIGN KEY (invitation_id) REFERENCES public.invitations(id);


--
-- Name: role_invitation_relationship role_invitation_relationship_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_invitation_relationship
    ADD CONSTRAINT role_invitation_relationship_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: role_provider_group_relationship role_provider_group_relationship_provider_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_provider_group_relationship
    ADD CONSTRAINT role_provider_group_relationship_provider_group_id_fkey FOREIGN KEY (provider_group_id) REFERENCES public.provider_groups(id);


--
-- Name: role_provider_group_relationship role_provider_group_relationship_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_provider_group_relationship
    ADD CONSTRAINT role_provider_group_relationship_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: role_user_relationship role_user_relationship_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_user_relationship
    ADD CONSTRAINT role_user_relationship_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: role_user_relationship role_user_relationship_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_user_relationship
    ADD CONSTRAINT role_user_relationship_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: roles roles_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: scan_summaries scan_summaries_scan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scan_summaries
    ADD CONSTRAINT scan_summaries_scan_id_fkey FOREIGN KEY (scan_id) REFERENCES public.scans(id);


--
-- Name: scans scans_provider_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scans
    ADD CONSTRAINT scans_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id);


--
-- Name: security_audit_logs security_audit_logs_resolved_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.security_audit_logs
    ADD CONSTRAINT security_audit_logs_resolved_by_id_fkey FOREIGN KEY (resolved_by_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: security_audit_logs security_audit_logs_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.security_audit_logs
    ADD CONSTRAINT security_audit_logs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE SET NULL;


--
-- Name: security_audit_logs security_audit_logs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.security_audit_logs
    ADD CONSTRAINT security_audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: tasks tasks_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: tenant_memberships tenant_memberships_invited_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_memberships
    ADD CONSTRAINT tenant_memberships_invited_by_id_fkey FOREIGN KEY (invited_by_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: users users_primary_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_primary_tenant_id_fkey FOREIGN KEY (primary_tenant_id) REFERENCES public.tenants(id);


--
-- PostgreSQL database dump complete
--

\unrestrict C3ROqTHgMhRzI30mwOm5MQ2lb0AwMxf9OaCvuQMAgz2rihfXVPhzV6BjkT2sgTO

