# Generated by Django 5.1.10 on 2025-08-26 16:58

import api.api_rls.row_level_security
import api.api_rls.security
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_add_user_trial_fields'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('django_celery_results', '0014_alter_taskresult_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='complianceoverview',
            name='rls_on_complianceoverview',
        ),
        migrations.RemoveConstraint(
            model_name='finding',
            name='rls_on_finding',
        ),
        migrations.RemoveConstraint(
            model_name='finding',
            name='rls_on_finding_default',
        ),
        migrations.RemoveConstraint(
            model_name='integration',
            name='rls_on_integration',
        ),
        migrations.RemoveConstraint(
            model_name='integrationproviderrelationship',
            name='rls_on_integrationproviderrelationship',
        ),
        migrations.RemoveConstraint(
            model_name='invitation',
            name='rls_on_invitation',
        ),
        migrations.RemoveConstraint(
            model_name='invitationrolerelationship',
            name='rls_on_invitationrolerelationship',
        ),
        migrations.RemoveConstraint(
            model_name='membership',
            name='statements_on_membership',
        ),
        migrations.RemoveConstraint(
            model_name='provider',
            name='rls_on_provider',
        ),
        migrations.RemoveConstraint(
            model_name='providergroup',
            name='rls_on_providergroup',
        ),
        migrations.RemoveConstraint(
            model_name='providergroupmembership',
            name='rls_on_providergroupmembership',
        ),
        migrations.RemoveConstraint(
            model_name='providersecret',
            name='rls_on_providersecret',
        ),
        migrations.RemoveConstraint(
            model_name='resource',
            name='rls_on_resource',
        ),
        migrations.RemoveConstraint(
            model_name='resourcefindingmapping',
            name='rls_on_resourcefindingmapping',
        ),
        migrations.RemoveConstraint(
            model_name='resourcefindingmapping',
            name='rls_on_resource_finding_mappings_default',
        ),
        migrations.RemoveConstraint(
            model_name='resourcescansummary',
            name='rls_on_resourcescansummary',
        ),
        migrations.RemoveConstraint(
            model_name='resourcetag',
            name='rls_on_resourcetag',
        ),
        migrations.RemoveConstraint(
            model_name='resourcetagmapping',
            name='rls_on_resourcetagmapping',
        ),
        migrations.RemoveConstraint(
            model_name='role',
            name='rls_on_role',
        ),
        migrations.RemoveConstraint(
            model_name='roleprovidergrouprelationship',
            name='rls_on_roleprovidergrouprelationship',
        ),
        migrations.RemoveConstraint(
            model_name='scan',
            name='rls_on_scan',
        ),
        migrations.RemoveConstraint(
            model_name='scansummary',
            name='rls_on_scansummary',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='rls_on_task',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='statements_on_user',
        ),
        migrations.RemoveConstraint(
            model_name='userrolerelationship',
            name='rls_on_userrolerelationship',
        ),
        migrations.RemoveField(
            model_name='complianceoverview',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='compliancerequirementoverview',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='integrationproviderrelationship',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='invitationrolerelationship',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='providergroup',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='providergroupmembership',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='providersecret',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='resourcefindingmapping',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='resourcescansummary',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='resourcetag',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='resourcetagmapping',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='role',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='roleprovidergrouprelationship',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='scansummary',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='userrolerelationship',
            name='tenant',
        ),
        migrations.AddField(
            model_name='complianceoverview',
            name='tenant_id',
            field=models.ForeignKey(default=1, help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compliancerequirementoverview',
            name='tenant_id',
            field=models.ForeignKey(default=1, help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finding',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integration',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrationproviderrelationship',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitationrolerelationship',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providergroup',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providergroupmembership',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providersecret',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcefindingmapping',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcescansummary',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcetag',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcetagmapping',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roleprovidergrouprelationship',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scansummary',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrolerelationship',
            name='tenant_id',
            field=models.ForeignKey(default='15970650-a9fa-4045-994f-c8e8a5009dec', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='complianceoverview',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_complianceoverview', statements=['SELECT', 'INSERT', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='compliancerequirementoverview',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_compliance', statements=['SELECT', 'INSERT', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Finding', statements=['SELECT', 'UPDATE', 'INSERT', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_modelname_default', partition_name='default', statements=['SELECT', 'UPDATE', 'INSERT', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='integration',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_integrations', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='integrationproviderrelationship',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_tanent', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ProviderSecret_new', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='invitationrolerelationship',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Role_RElationship', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=api.api_rls.security.BaseSecurityConstraint(name='statements_on_tanent_contraints', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_provider_tenant', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='providergroup',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ProviderGroup', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='providergroupmembership',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ProviderGroupMembership', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='providersecret',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ProviderSecret', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Resource', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcefindingmapping',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ResourceFindingMapping', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcefindingmapping',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(name='rls_on_resource_finding_mappings_default', partition_name='default', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcescansummary',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_Row_level', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcetag',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ResourceTag', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcetagmapping',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ResourceTagMapping', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Provider_Secret', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='roleprovidergrouprelationship',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Role_Provider', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='scan',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Scan', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='scansummary',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_scan', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Task', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=api.api_rls.security.BaseSecurityConstraint(name='statements_on_constraints', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='userrolerelationship',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Role_Provider_Group', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
    ]
