# Generated by Django 5.1.10 on 2025-08-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_complianceoverview_rls_on_complianceoverview_and_more'),
    ]

    operations = [
    ]
