# Generated by Django 5.1.10 on 2025-09-27 18:39

import api.api_rls.row_level_security
import api.api_rls.security
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_auditlog_company_remove_auditlog_user_and_more'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('django_celery_results', '0014_alter_taskresult_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureOAuthConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_name', models.CharField(db_index=True, max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.TextField()),
                ('tenant_id', models.CharField(max_length=255)),
                ('redirect_uri', models.CharField(max_length=500)),
                ('scopes', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'azure_oauth_configs',
            },
        ),
        migrations.RemoveConstraint(
            model_name='complianceoverview',
            name='rls_on_complianceoverview',
        ),
        migrations.RemoveConstraint(
            model_name='compliancerequirementoverview',
            name='rls_on_compliance',
        ),
        migrations.RemoveConstraint(
            model_name='finding',
            name='rls_on_Finding',
        ),
        migrations.RemoveConstraint(
            model_name='finding',
            name='rls_on_modelname_default',
        ),
        migrations.RemoveConstraint(
            model_name='integration',
            name='rls_on_integrations',
        ),
        migrations.RemoveConstraint(
            model_name='integrationproviderrelationship',
            name='rls_on_tanent',
        ),
        migrations.RemoveConstraint(
            model_name='invitation',
            name='rls_on_ProviderSecret_new',
        ),
        migrations.RemoveConstraint(
            model_name='invitationrolerelationship',
            name='rls_on_Role_RElationship',
        ),
        migrations.RemoveConstraint(
            model_name='membership',
            name='statements_on_tanent_contraints',
        ),
        migrations.RemoveConstraint(
            model_name='provider',
            name='rls_provider_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='providergroup',
            name='rls_on_ProviderGroup',
        ),
        migrations.RemoveConstraint(
            model_name='providergroupmembership',
            name='rls_on_ProviderGroupMembership',
        ),
        migrations.RemoveConstraint(
            model_name='providersecret',
            name='rls_on_ProviderSecret',
        ),
        migrations.RemoveConstraint(
            model_name='resource',
            name='rls_on_Resource',
        ),
        migrations.RemoveConstraint(
            model_name='resourcefindingmapping',
            name='rls_on_ResourceFindingMapping',
        ),
        migrations.RemoveConstraint(
            model_name='resourcefindingmapping',
            name='rls_on_resource_finding_mappings_default',
        ),
        migrations.RemoveConstraint(
            model_name='resourcescansummary',
            name='rls_Row_level',
        ),
        migrations.RemoveConstraint(
            model_name='resourcetag',
            name='rls_on_ResourceTag',
        ),
        migrations.RemoveConstraint(
            model_name='resourcetagmapping',
            name='rls_on_ResourceTagMapping',
        ),
        migrations.RemoveConstraint(
            model_name='role',
            name='rls_on_Provider_Secret',
        ),
        migrations.RemoveConstraint(
            model_name='roleprovidergrouprelationship',
            name='rls_on_Role_Provider',
        ),
        migrations.RemoveConstraint(
            model_name='scan',
            name='rls_on_Scan',
        ),
        migrations.RemoveConstraint(
            model_name='scansummary',
            name='rls_on_scan',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='rls_on_Task',
        ),
        migrations.RemoveConstraint(
            model_name='tenant',
            name='statements_on_constraints',
        ),
        migrations.RemoveConstraint(
            model_name='userrolerelationship',
            name='rls_on_Role_Provider_Group',
        ),
        migrations.AddField(
            model_name='invitation',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='invitation_roles', through='api.InvitationRoleRelationship', to='api.role'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='domain',
            field=models.CharField(blank=True, help_text="Custom domain for production (e.g., 'company1.example.com')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(blank=True, help_text="Subdomain for multi-tenant access (e.g., 'company1' for company1.localhost:3000)", max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='When the trial period ends', null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='invitations',
            field=models.ManyToManyField(related_name='role_invitations', through='api.InvitationRoleRelationship', to='api.invitation'),
        ),
        migrations.AddConstraint(
            model_name='complianceoverview',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_complianceoverview', statements=['SELECT', 'INSERT', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='compliancerequirementoverview',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_compliance', statements=['SELECT', 'INSERT', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Finding', statements=['SELECT', 'UPDATE', 'INSERT', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_modelname_default', partition_name='default', statements=['SELECT', 'UPDATE', 'INSERT', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='integration',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_integrations', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='integrationproviderrelationship',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_tanent', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ProviderSecret_new', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='invitationrolerelationship',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Role_RElationship', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=api.api_rls.security.BaseSecurityConstraint(name='statements_on_tanent_contraints', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_provider_tenant', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='providergroup',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ProviderGroup', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='providergroupmembership',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ProviderGroupMembership', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='providersecret',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ProviderSecret', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Resource', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcefindingmapping',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ResourceFindingMapping', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcefindingmapping',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(name='rls_on_resource_finding_mappings_default', partition_name='default', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcescansummary',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_Row_level', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcetag',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ResourceTag', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcetagmapping',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ResourceTagMapping', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Provider_Secret', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='roleprovidergrouprelationship',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Role_Provider', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='scan',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Scan', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='scansummary',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_scan', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Task', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=api.api_rls.security.BaseSecurityConstraint(name='statements_on_constraints', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='userrolerelationship',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Role_Provider_Group', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AlterUniqueTogether(
            name='azureoauthconfig',
            unique_together={('tenant_name',)},
        ),
    ]
