# Generated by Django 5.1.10 on 2025-10-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_tenant_configuration_fields'),
        ('api', '0048_add_tenant_configuration_fields'),
    ]

    operations = [
    ]
