# Generated by Django 5.1.10 on 2025-10-09 15:12

import api.api_rls.row_level_security
import api.api_rls.security
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_merge_20251009_2030'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('django_celery_results', '0014_alter_taskresult_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('can_invite_users', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tenant_memberships',
            },
        ),
        migrations.CreateModel(
            name='TenantOAuthConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('azure', 'Azure AD (Microsoft Entra ID)'), ('google', 'Google OAuth'), ('github', 'GitHub OAuth'), ('okta', 'Okta'), ('auth0', 'Auth0')], help_text='OAuth provider type', max_length=50)),
                ('client_id', models.CharField(help_text='OAuth Client ID', max_length=255)),
                ('_client_secret', models.BinaryField(db_column='client_secret', help_text='Encrypted OAuth Client Secret')),
                ('redirect_uri', models.URLField(help_text='OAuth Redirect URI')),
                ('provider_tenant_id', models.CharField(blank=True, help_text='Provider-specific tenant ID (e.g., Azure tenant ID)', max_length=255, null=True)),
                ('scopes', models.JSONField(default=list, help_text='OAuth scopes to request')),
                ('allowed_domains', models.JSONField(default=list, help_text='Allowed email domains for this provider')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this config is active')),
                ('auto_create_users', models.BooleanField(default=True, help_text='Automatically create users on first login')),
                ('require_email_verification', models.BooleanField(default=False, help_text='Require email verification for new users')),
                ('additional_params', models.JSONField(default=dict, help_text='Additional OAuth parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tenant_oauth_configs',
            },
        ),
        migrations.CreateModel(
            name='TenantOAuthUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_user_id', models.CharField(help_text='User ID from the OAuth provider', max_length=255)),
                ('provider_email', models.EmailField(help_text='Email from the OAuth provider', max_length=254)),
                ('_access_token', models.BinaryField(blank=True, db_column='access_token', help_text='Encrypted access token', null=True)),
                ('_refresh_token', models.BinaryField(blank=True, db_column='refresh_token', help_text='Encrypted refresh token', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_oauth_users',
            },
        ),
        migrations.RemoveConstraint(
            model_name='complianceoverview',
            name='rls_on_complianceoverview',
        ),
        migrations.RemoveConstraint(
            model_name='compliancerequirementoverview',
            name='rls_on_compliance',
        ),
        migrations.RemoveConstraint(
            model_name='finding',
            name='rls_on_Finding',
        ),
        migrations.RemoveConstraint(
            model_name='finding',
            name='rls_on_modelname_default',
        ),
        migrations.RemoveConstraint(
            model_name='integration',
            name='rls_on_integrations',
        ),
        migrations.RemoveConstraint(
            model_name='integrationproviderrelationship',
            name='rls_on_tanent',
        ),
        migrations.RemoveConstraint(
            model_name='invitation',
            name='rls_on_ProviderSecret_new',
        ),
        migrations.RemoveConstraint(
            model_name='invitationrolerelationship',
            name='rls_on_Role_RElationship',
        ),
        migrations.RemoveConstraint(
            model_name='membership',
            name='statements_on_tanent_contraints',
        ),
        migrations.RemoveConstraint(
            model_name='provider',
            name='rls_provider_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='providergroup',
            name='rls_on_ProviderGroup',
        ),
        migrations.RemoveConstraint(
            model_name='providergroupmembership',
            name='rls_on_ProviderGroupMembership',
        ),
        migrations.RemoveConstraint(
            model_name='providersecret',
            name='rls_on_ProviderSecret',
        ),
        migrations.RemoveConstraint(
            model_name='resource',
            name='rls_on_Resource',
        ),
        migrations.RemoveConstraint(
            model_name='resourcefindingmapping',
            name='rls_on_ResourceFindingMapping',
        ),
        migrations.RemoveConstraint(
            model_name='resourcefindingmapping',
            name='rls_on_resource_finding_mappings_default',
        ),
        migrations.RemoveConstraint(
            model_name='resourcescansummary',
            name='rls_Row_level',
        ),
        migrations.RemoveConstraint(
            model_name='resourcetag',
            name='rls_on_ResourceTag',
        ),
        migrations.RemoveConstraint(
            model_name='resourcetagmapping',
            name='rls_on_ResourceTagMapping',
        ),
        migrations.RemoveConstraint(
            model_name='role',
            name='rls_on_Provider_Secret',
        ),
        migrations.RemoveConstraint(
            model_name='roleprovidergrouprelationship',
            name='rls_on_Role_Provider',
        ),
        migrations.RemoveConstraint(
            model_name='scan',
            name='rls_on_Scan',
        ),
        migrations.RemoveConstraint(
            model_name='scansummary',
            name='rls_on_scan',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='rls_on_Task',
        ),
        migrations.RemoveConstraint(
            model_name='tenant',
            name='statements_on_constraints',
        ),
        migrations.RemoveConstraint(
            model_name='userrolerelationship',
            name='rls_on_Role_Provider_Group',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='admin_user',
        ),
        migrations.AddField(
            model_name='tenant',
            name='allow_registration',
            field=models.BooleanField(default=True, help_text='Allow new user registration'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='require_email_verification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='session_timeout_minutes',
            field=models.IntegerField(default=480, help_text='Session timeout in minutes'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Email verification status'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_tenant',
            field=models.ForeignKey(blank=True, help_text="User's primary tenant", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='api.tenant'),
        ),
        migrations.AlterField(
            model_name='role',
            name='invitations',
            field=models.ManyToManyField(related_name='roles', through='api.InvitationRoleRelationship', to='api.invitation'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(default='admin@example.com', help_text='Primary contact email', max_length=254),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='domain',
            field=models.CharField(blank=True, help_text='Custom domain (optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether tenant is active'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether tenant is verified'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(help_text='Organization name', max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='secondary_color',
            field=models.CharField(default='#1E40AF', help_text='Secondary theme color', max_length=7),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(default='default', help_text="Subdomain for tenant isolation (e.g., 'company1')", max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='theme_color',
            field=models.CharField(default='#3B82F6', help_text='Primary theme color', max_length=7),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['subdomain'], name='tenants_subdoma_69cf01_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active'], name='tenants_is_acti_ec1713_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['subscription_status'], name='tenants_subscri_f58e68_idx'),
        ),
        migrations.AddConstraint(
            model_name='complianceoverview',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_complianceoverview', statements=['SELECT', 'INSERT', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='compliancerequirementoverview',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_compliance', statements=['SELECT', 'INSERT', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Finding', statements=['SELECT', 'UPDATE', 'INSERT', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_modelname_default', partition_name='default', statements=['SELECT', 'UPDATE', 'INSERT', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='integration',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_integrations', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='integrationproviderrelationship',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_tanent', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ProviderSecret_new', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='invitationrolerelationship',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Role_RElationship', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=api.api_rls.security.BaseSecurityConstraint(name='statements_on_tanent_contraints', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_provider_tenant', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='providergroup',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ProviderGroup', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='providergroupmembership',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ProviderGroupMembership', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='providersecret',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ProviderSecret', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Resource', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcefindingmapping',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ResourceFindingMapping', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcefindingmapping',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(name='rls_on_resource_finding_mappings_default', partition_name='default', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcescansummary',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_Row_level', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcetag',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ResourceTag', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcetagmapping',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ResourceTagMapping', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Provider_Secret', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='roleprovidergrouprelationship',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Role_Provider', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='scan',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Scan', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='scansummary',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_scan', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Task', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=api.api_rls.security.BaseSecurityConstraint(name='statements_on_constraints', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='userrolerelationship',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Role_Provider_Group', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.tenant'),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantoauthconfig',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_oauth_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantoauthconfig',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this OAuth config belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='oauth_configs', to='api.tenant'),
        ),
        migrations.AddField(
            model_name='tenantoauthuser',
            name='oauth_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_users', to='api.tenantoauthconfig'),
        ),
        migrations.AddField(
            model_name='tenantoauthuser',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_users', to='api.tenant'),
        ),
        migrations.AddField(
            model_name='tenantoauthuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_oauth_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['user', 'tenant'], name='tenant_memb_user_id_7fcafa_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant', 'is_active'], name='tenant_memb_tenant__c6bbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['role'], name='tenant_memb_role_a11bcc_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(fields=('user', 'tenant'), name='unique_user_tenant_membership'),
        ),
        migrations.AddIndex(
            model_name='tenantoauthconfig',
            index=models.Index(fields=['tenant', 'provider'], name='tenant_oaut_tenant__1c7c74_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantoauthconfig',
            index=models.Index(fields=['tenant', 'is_active'], name='tenant_oaut_tenant__bc318e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantoauthconfig',
            index=models.Index(fields=['provider'], name='tenant_oaut_provide_4d077f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantoauthconfig',
            unique_together={('tenant', 'provider')},
        ),
        migrations.AddIndex(
            model_name='tenantoauthuser',
            index=models.Index(fields=['tenant', 'user'], name='tenant_oaut_tenant__9af663_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantoauthuser',
            index=models.Index(fields=['tenant', 'oauth_config'], name='tenant_oaut_tenant__420aae_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantoauthuser',
            index=models.Index(fields=['provider_user_id'], name='tenant_oaut_provide_a93078_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantoauthuser',
            unique_together={('tenant', 'oauth_config', 'provider_user_id')},
        ),
    ]
