# Generated by Django 5.1.10 on 2025-10-09 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_tenantmembership_tenantoauthconfig_tenantoauthuser_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE tenants ADD COLUMN IF NOT EXISTS subscription_status VARCHAR(20) DEFAULT 'trial';
            ALTER TABLE tenants ADD COLUMN IF NOT EXISTS allow_registration BOOLEAN DEFAULT true;
            ALTER TABLE tenants ADD COLUMN IF NOT EXISTS require_email_verification BOOLEAN DEFAULT false;
            ALTER TABLE tenants ADD COLUMN IF NOT EXISTS session_timeout_minutes INTEGER DEFAULT 480;
            ALTER TABLE tenants ADD COLUMN IF NOT EXISTS created_by_id UUID;
            ALTER TABLE tenants ADD COLUMN IF NOT EXISTS last_activity TIMESTAMP WITH TIME ZONE;
            """,
            reverse_sql="""
            ALTER TABLE tenants DROP COLUMN IF EXISTS subscription_status;
            ALTER TABLE tenants DROP COLUMN IF EXISTS allow_registration;
            ALTER TABLE tenants DROP COLUMN IF EXISTS require_email_verification;
            ALTER TABLE tenants DROP COLUMN IF EXISTS session_timeout_minutes;
            ALTER TABLE tenants DROP COLUMN IF EXISTS created_by_id;
            ALTER TABLE tenants DROP COLUMN IF EXISTS last_activity;
            """
        ),
    ]
