# Generated by Django 5.1.10 on 2025-10-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_remove_complianceoverview_rls_on_complianceoverview_and_more'),
    ]

    operations = [
    ]
