# Generated by Django 5.1.10 on 2025-10-13 21:20

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_merge_20251014_0228'),
    ]

    operations = [
        # Add missing fields to Tenant model
        migrations.AddField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_users',
            field=models.PositiveIntegerField(default=5, help_text='Maximum users allowed for this tenant'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_providers',
            field=models.PositiveIntegerField(default=3, help_text='Maximum cloud providers allowed'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=480, help_text='Session timeout in minutes'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='require_email_verification',
            field=models.BooleanField(default=True, help_text='Require email verification for new users'),
        ),
    ]
