# Generated by Django 5.1.10 on 2025-10-13 21:27

import api.api_rls.row_level_security
import api.api_rls.security
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20251014_0250'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('django_celery_results', '0014_alter_taskresult_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('login_success', 'Successful Login'), ('login_failed', 'Failed Login'), ('login_blocked', 'Login Blocked'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('password_changed', 'Password Changed'), ('tenant_access_denied', 'Tenant Access Denied'), ('tenant_switched', 'Tenant Switched'), ('permission_denied', 'Permission Denied'), ('data_access_violation', 'Data Access Violation'), ('api_rate_limit', 'API Rate Limit Exceeded'), ('suspicious_activity', 'Suspicious Activity'), ('security_scan', 'Security Scan'), ('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('tenant_created', 'Tenant Created'), ('tenant_modified', 'Tenant Modified'), ('tenant_deleted', 'Tenant Deleted'), ('oauth_login', 'OAuth Login'), ('oauth_failed', 'OAuth Failed'), ('two_factor_enabled', '2FA Enabled'), ('two_factor_disabled', '2FA Disabled'), ('admin_action', 'Admin Action'), ('system_error', 'System Error')], db_index=True, help_text='Type of security event', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', help_text='Severity level of the event', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request', null=True)),
                ('request_path', models.CharField(blank=True, help_text='Request path that triggered the event', max_length=500, null=True)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method of the request', max_length=10, null=True)),
                ('message', models.TextField(help_text='Human-readable description of the event')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the event')),
                ('is_security_violation', models.BooleanField(db_index=True, default=False, help_text='Whether this event represents a security violation')),
                ('requires_investigation', models.BooleanField(db_index=True, default=False, help_text='Whether this event requires manual investigation')),
                ('resolved', models.BooleanField(db_index=True, default=False, help_text='Whether this event has been resolved')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When this event was resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how this event was resolved', null=True)),
            ],
            options={
                'db_table': 'security_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='complianceoverview',
            name='rls_on_complianceoverview',
        ),
        migrations.RemoveConstraint(
            model_name='compliancerequirementoverview',
            name='rls_on_compliance',
        ),
        migrations.RemoveConstraint(
            model_name='finding',
            name='rls_on_Finding',
        ),
        migrations.RemoveConstraint(
            model_name='finding',
            name='rls_on_modelname_default',
        ),
        migrations.RemoveConstraint(
            model_name='integration',
            name='rls_on_integrations',
        ),
        migrations.RemoveConstraint(
            model_name='integrationproviderrelationship',
            name='rls_on_tanent',
        ),
        migrations.RemoveConstraint(
            model_name='invitation',
            name='rls_on_ProviderSecret_new',
        ),
        migrations.RemoveConstraint(
            model_name='invitationrolerelationship',
            name='rls_on_Role_RElationship',
        ),
        migrations.RemoveConstraint(
            model_name='membership',
            name='statements_on_tanent_contraints',
        ),
        migrations.RemoveConstraint(
            model_name='provider',
            name='rls_provider_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='providergroup',
            name='rls_on_ProviderGroup',
        ),
        migrations.RemoveConstraint(
            model_name='providergroupmembership',
            name='rls_on_ProviderGroupMembership',
        ),
        migrations.RemoveConstraint(
            model_name='providersecret',
            name='rls_on_ProviderSecret',
        ),
        migrations.RemoveConstraint(
            model_name='resource',
            name='rls_on_Resource',
        ),
        migrations.RemoveConstraint(
            model_name='resourcefindingmapping',
            name='rls_on_ResourceFindingMapping',
        ),
        migrations.RemoveConstraint(
            model_name='resourcefindingmapping',
            name='rls_on_resource_finding_mappings_default',
        ),
        migrations.RemoveConstraint(
            model_name='resourcescansummary',
            name='rls_Row_level',
        ),
        migrations.RemoveConstraint(
            model_name='resourcetag',
            name='rls_on_ResourceTag',
        ),
        migrations.RemoveConstraint(
            model_name='resourcetagmapping',
            name='rls_on_ResourceTagMapping',
        ),
        migrations.RemoveConstraint(
            model_name='role',
            name='rls_on_Provider_Secret',
        ),
        migrations.RemoveConstraint(
            model_name='roleprovidergrouprelationship',
            name='rls_on_Role_Provider',
        ),
        migrations.RemoveConstraint(
            model_name='scan',
            name='rls_on_Scan',
        ),
        migrations.RemoveConstraint(
            model_name='scansummary',
            name='rls_on_scan',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='rls_on_Task',
        ),
        migrations.RemoveConstraint(
            model_name='tenant',
            name='statements_on_constraints',
        ),
        migrations.RemoveConstraint(
            model_name='tenantmembership',
            name='unique_user_tenant_membership',
        ),
        migrations.RemoveConstraint(
            model_name='userrolerelationship',
            name='rls_on_Role_Provider_Group',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='idx_tenant_subdomain',
            old_name='tenants_subdoma_69cf01_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='idx_tenant_active',
            old_name='tenants_is_acti_ec1713_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='idx_tenant_subscription',
            old_name='tenants_subscri_f58e68_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantmembership',
            new_name='idx_membership_user_tenant',
            old_name='tenant_memb_user_id_7fcafa_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_security_scan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='lockout_duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Account lockout duration in minutes'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_failed_login_attempts',
            field=models.PositiveIntegerField(default=5, help_text='Maximum failed login attempts before account lockout'),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='can_manage_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='can_manage_integrations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='can_manage_providers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='can_manage_scans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='can_manage_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='unlimited_visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_security_scan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tenants',
            field=models.ManyToManyField(blank=True, help_text='All tenants this user has access to', related_name='members', through='api.TenantMembership', to='api.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Whether two-factor authentication is enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, help_text='TOTP secret for 2FA', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Username (auto-generated from email if not provided)', max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(help_text='Primary contact email for tenant', max_length=254),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='domain',
            field=models.CharField(blank=True, help_text='Custom domain (optional, must be unique if provided)', max_length=253, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether tenant is active - inactive tenants cannot login'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether tenant is verified by admin'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(db_index=True, help_text='Organization name (must be unique)', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='secondary_color',
            field=models.CharField(default='#1E40AF', help_text='Secondary theme color', max_length=7, validators=[django.core.validators.RegexValidator(message='Secondary color must be a valid hex color code', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(db_index=True, help_text="Subdomain for tenant isolation (e.g., 'company1')", max_length=63, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_subdomain', message='Subdomain must be lowercase alphanumeric with hyphens, no spaces', regex='^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], db_index=True, default='trial', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='theme_color',
            field=models.CharField(default='#3B82F6', help_text='Primary theme color', max_length=7, validators=[django.core.validators.RegexValidator(message='Theme color must be a valid hex color code', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to='api.tenant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='Email address (case insensitive)', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of consecutive failed login attempts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Email verification status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_tenant',
            field=models.ForeignKey(help_text='Primary tenant this user belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='api.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantmembership',
            unique_together={('user', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['created_at'], name='idx_tenant_created'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['last_activity'], name='idx_tenant_activity'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['primary_tenant'], name='idx_user_tenant'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='idx_user_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='idx_user_verified'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_login'], name='idx_user_last_login'),
        ),
        migrations.AddConstraint(
            model_name='complianceoverview',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_complianceoverview', statements=['SELECT', 'INSERT', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='compliancerequirementoverview',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_compliance', statements=['SELECT', 'INSERT', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Finding', statements=['SELECT', 'UPDATE', 'INSERT', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_modelname_default', partition_name='default', statements=['SELECT', 'UPDATE', 'INSERT', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='integration',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_integrations', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='integrationproviderrelationship',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_tanent', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ProviderSecret_new', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='invitationrolerelationship',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Role_RElationship', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=api.api_rls.security.BaseSecurityConstraint(name='statements_on_tanent_contraints', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_provider_tenant', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='providergroup',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ProviderGroup', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='providergroupmembership',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ProviderGroupMembership', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='providersecret',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ProviderSecret', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Resource', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcefindingmapping',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ResourceFindingMapping', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcefindingmapping',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(name='rls_on_resource_finding_mappings_default', partition_name='default', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcescansummary',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_Row_level', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcetag',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ResourceTag', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='resourcetagmapping',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_ResourceTagMapping', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Provider_Secret', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='roleprovidergrouprelationship',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Role_Provider', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='scan',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Scan', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='scansummary',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_scan', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Task', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=api.api_rls.security.BaseSecurityConstraint(name='statements_on_constraints', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('failed_login_attempts__gte', 0)), name='user_failed_attempts_positive'),
        ),
        migrations.AddConstraint(
            model_name='userrolerelationship',
            constraint=api.api_rls.row_level_security.RowLevelSecurityConstraint(field='tenant_id', name='rls_on_Role_Provider_Group', statements=['SELECT', 'INSERT', 'UPDATE', 'DELETE']),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='User who resolved this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant context of the event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to='api.tenant'),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User involved in the event (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['timestamp'], name='idx_audit_timestamp'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['event_type'], name='idx_audit_event_type'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['severity'], name='idx_audit_severity'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['user'], name='idx_audit_user'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['tenant'], name='idx_audit_tenant'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['is_security_violation'], name='idx_audit_violation'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['requires_investigation'], name='idx_audit_investigation'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['resolved'], name='idx_audit_resolved'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['ip_address'], name='idx_audit_ip'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['timestamp', 'event_type'], name='idx_audit_timestamp_event'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['tenant', 'timestamp'], name='idx_audit_tenant_timestamp'),
        ),
    ]
