# Generated by Django 5.1.10 on 2025-10-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_azure_ad_sso_integration'),
        ('api', '0061_remove_complianceoverview_rls_on_complianceoverview_and_more'),
    ]

    operations = [
    ]
